name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - run: npm install
      - run: npm run lint

  test-node:
    runs-on: ubuntu-latest
    name: Node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - run: npm i
      - run: npm run test:node

  test-bare:
    runs-on: ubuntu-latest
    name: Bare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - run: npm i
      - run: npm i -g bare
      - run: npm run test:bare
