name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: |
          npm run lint

  test-node:
    runs-on: ubuntu-latest
    name: Node
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm run test:node

  test-bare:
    runs-on: ubuntu-latest
    name: Bare
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Install bare
        run: npm i -g bare

      - name: Test
        run: npm run test:bare
